name: Continuous Integration

on: [push, pull_request]

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Setup Scala
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.8
      - name: Cache Scala
        uses: coursier/cache-action@v5
      - name: Install verilator
        run: sudo apt install verilator -y
      - name: Install RISC-V toolchain
        run: |
          wget https://github.com/stnolting/riscv-gcc-prebuilt/releases/download/rv32i-4.0.0/riscv32-unknown-elf.gcc-12.1.0.tar.gz
          sudo mkdir /opt/riscv
          sudo tar -xzf riscv32-unknown-elf.gcc-12.1.0.tar.gz -C /opt/riscv/
          rm  riscv32-unknown-elf.gcc-12.1.0.tar.gz
          root=$(pwd)
          echo "PATH=$PATH:/opt/riscv/bin" >> $GITHUB_ENV
          echo "FLEXPRET_ROOT_DIR=$root/flexpret" >> $GITHUB_ENV
          echo "INTERPRET_ROOT_DIR=$root" >> $GITHUB_ENV
      - name: Build and test FlexPRET
        run : |
          cd $FLEXPRET_ROOT_DIR
          make clean && make emulator
          make test
      - name: Build and test InterPRET
        run: |
          make emulator N_CORES=4 THREADS=4 FLEX=false TRACE=0
          make unit-tests
          make integration-tests